# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main
- pr

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'BarBStyle.Color.Theme.csproj'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET 6 Core sdk'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true

- task: NuGetToolInstaller@1
  displayName: 'Instalando NuGet'

- task: NuGetCommand@2
  displayName: 'Restaurando NuGet'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: VSBuild@1
  displayName: 'Fazendo build'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'Empacotando NuGet'
  inputs:
    command: 'pack'
    packagesToPack: '**/BarBStyle.Colors.Theme.nuspec'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
    allowPackageConflicts: true
    packDestination: '$(Build.ArtifactStagingDirectory)'

    
# - task: NuGetCommand@2
#   displayName: 'Enviando NuGet'
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'BarbBStyle'

- script: |
    npm install -g conventional-changelog-cli
    conventional-changelog -p angular -i $(Build.ArtifactStagingDirectory)/CHANGELOG.md -s
  displayName: 'Generate Release Notes'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**/*.md'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/ReleaseNotes'
  displayName: 'Copy Release Notes'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/ReleaseNotes'
    artifact: 'ReleaseNotes'
  displayName: 'Publish Release Notes Artifact'

